Feature/tab
toggle-corp/toggle-ui pull request #12
Opened 2020-08-28 03:36 UTC by frozenhelium

2020-08-31 09:26 UTC, tnagorra commented on src/components/List.tsx
> +        children.push(...groups[groupKey].map(renderListItem));
While creating children inside grouped list, the key should change when group changes

2020-08-31 09:29 UTC, tnagorra commented on src/components/Tab/index.tsx
> +const tabContext = React.createContext({
```suggestion
const TabContext = React.createContext({
```

2020-08-31 09:30 UTC, tnagorra commented on src/components/Tab/index.tsx
> +const tabContext = React.createContext({
or we should destructure tabContext before using it in jsx

Bad:
         <tabContext.Provider value={contextValue}> 
Good:
        <Provider value={contexValue}>

2020-09-01 03:57 UTC, tnagorra commented on src/components/List.tsx
> +List.defaultProps = {
Let's not use defaultProps

2020-09-01 08:17 UTC, tnagorra commented on src/components/Tabs/index.tsx
> +type TabKey = string | undefined;
Shouldn't TabKey always be defined?

2020-09-01 08:19 UTC, tnagorra requested changes
Typing issues should be resolved first.

2020-09-01 10:12 UTC, frozenhelium commented on src/components/Tabs/index.tsx
> +type TabKey = string | undefined;
No tab can be visible as well

2020-09-01 11:10 UTC, tnagorra approved these changes

2020-09-01 11:15 UTC, merged