Add row expansion hooks for table
toggle-corp/toggle-ui pull request #73
Opened 2021-07-02 03:23 UTC by frozenhelium

## Changes

* Add hooks for row expansion
* Separate tr, th, td to separate components
* Improve styling

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] UI changes

2021-07-02 04:16 UTC, AdityaKhatri approved these changes

2021-07-02 05:46 UTC, tnagorra commented on src/components/Table/useRowExpansionOnClick.tsx
> +                    },
We should separately memoize this funciton

2021-07-02 05:48 UTC, tnagorra approved these changes

2021-07-02 08:31 UTC, tnagorra requested changes
Let's add a story for expandable table row with button

2021-07-05 06:40 UTC, tnagorra approved these changes

2021-07-05 07:49 UTC, merged