Add resizable column in table
toggle-corp/toggle-ui pull request #75
Opened 2021-07-14 09:53 UTC by frozenhelium

## Changes

* Add option for column resize in table
* Remove first and last border in table

## This PR doesn't introduce any:

- [x] temporary files, auto-generated files or secret keys
- [x] build works
- [x] eslint issues
- [x] typescript issues
- [x] `console.log` meant for debugging
- [x] typos
- [x] unwanted comments

## This PR contains valid:

- [x] UI changes

2021-07-15 10:04 UTC, AdityaKhatri commented
@frozenhelium ,
1. There should be a minimum width and whenever items overlap, overlapped content should not be shown
2. Make resize border larger

2021-07-15 10:07 UTC, priyesh777 approved these changes

2021-07-16 06:52 UTC, frozenhelium commented
@AdityaKhatri 

1. Minimum with is possible through css `min-width`
2. Resize border is actually larger (triggers on 4px) but it appears 1px visually. Should we make it visually large as well?

2021-07-19 04:22 UTC, tnagorra commented on src/components/Table/useColumnResize.ts
> +    ), [columns, columnWidths]);
I think we shouldn't do this.

2021-07-23 05:59 UTC, tnagorra requested changes

2021-07-23 05:59 UTC, tnagorra commented on src/components/Table/index.tsx
> +    ), [columns, columnWidths]);
How about we create a separate mapping with all of the defaults?
Currently there are ways the calculation of width may be inconsistent.

2021-07-23 06:04 UTC, tnagorra commented
Let's also add default min-size on columns.
Let's also add background color so that the contents don't overlap with each other when column sizes are too small

2021-07-29 06:04 UTC, merged